name: Kirby 64 Pull Request CI

on:
  pull_request_target:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - name: Download Qemu Irix
      run: wget https://github.com/n64decomp/qemu-irix/releases/download/v2.11-deb/qemu-irix-2.11.0-2169-g32ab296eef_amd64.deb
    - name: Install Qemu Irix
      run: sudo dpkg -i qemu-irix-2.11.0-2169-g32ab296eef_amd64.deb
    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y binutils-mips-linux-gnu gcc git gcc-mips-linux-gnu
    - name: Install Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Python Dependencies
      run: pip3 install gitpython
    - name: Install Splat Dependencies
      run: pip3 install -r splat/requirements.txt
    - name: More Dependencies
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.SECRETREPO }}
        token: ${{ secrets.SECRETTOKEN }}
        path: dep
    - name: Get the dependency
      run: cp dep/${{ secrets.ANOTHERSECRET }} .
    - name: Build Libultra
      run: make -C libreultra -j4
    - name: Build Naudio
      run: make -C libreultra naudio -j4
    - name: Build Tools
      run: make -C tools -j4
    - name: Assemble F3DEX2
      run: make -C f3dex2 VERSION=2.04H ARMIPS=../tools/armips
    - name: Prepare Kirby 64 for building
      run: make setup
    - name: Build Kirby 64
      run: ./rebuild.sh
